"""refund ticket

Revision ID: 0f340ae580bf
Revises: 99220b94bb5e
Create Date: 2022-07-07 13:12:38.589002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f340ae580bf'
down_revision = '99220b94bb5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refunded_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('refund_timestamp', sa.DateTime(), nullable=False),
    sa.Column('refund_amount', sa.Float(), nullable=False),
    sa.Column('refunded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['refunded_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['purchased_ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refunded_ticket')
    # ### end Alembic commands ###
