"""indexes

Revision ID: 1d5faa7e879b
Revises: 0f340ae580bf
Create Date: 2022-07-12 21:29:18.268948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d5faa7e879b'
down_revision = '0f340ae580bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_flight_departure_time'), 'flight', ['departure_time'], unique=False)
    op.create_index(op.f('ix_flight_end'), 'flight', ['end'], unique=False)
    op.create_index(op.f('ix_flight_start'), 'flight', ['start'], unique=False)
    op.create_index(op.f('ix_purchased_ticket_departure_date'), 'purchased_ticket', ['departure_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchased_ticket_departure_date'), table_name='purchased_ticket')
    op.drop_index(op.f('ix_flight_start'), table_name='flight')
    op.drop_index(op.f('ix_flight_end'), table_name='flight')
    op.drop_index(op.f('ix_flight_departure_time'), table_name='flight')
    # ### end Alembic commands ###
