"""drop base fare

Revision ID: 50ec223d54a8
Revises: c10beb6f188b
Create Date: 2022-07-21 09:18:12.689456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50ec223d54a8'
down_revision = 'c10beb6f188b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_transaction', 'base_fare')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_transaction', sa.Column('base_fare', mysql.FLOAT(), nullable=False))
    # ### end Alembic commands ###
