"""purchase flight

Revision ID: 99220b94bb5e
Revises: a99927aa2a16
Create Date: 2022-06-28 07:47:47.448573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99220b94bb5e'
down_revision = 'a99927aa2a16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchased_flight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('purchased_by', sa.Integer(), nullable=True),
    sa.Column('purchase_timestamp', sa.DateTime(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('assisted_by', sa.Integer(), nullable=True),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['assisted_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.id'], ),
    sa.ForeignKeyConstraint(['purchased_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchased_flight')
    # ### end Alembic commands ###
