"""base

Revision ID: a736dd8077fe
Revises: 
Create Date: 2022-07-14 17:08:48.408069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a736dd8077fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airplane',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=120), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('model_code', sa.String(length=120), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('range', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airplane_registration_number'), 'airplane', ['registration_number'], unique=True)
    op.create_table('airport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airport_code'), 'airport', ['code'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=4), nullable=True),
    sa.Column('airplane_id', sa.Integer(), nullable=True),
    sa.Column('departure_id', sa.Integer(), nullable=True),
    sa.Column('arrival_id', sa.Integer(), nullable=True),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('end', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['airplane_id'], ['airplane.id'], ),
    sa.ForeignKeyConstraint(['arrival_id'], ['airport.id'], ),
    sa.ForeignKeyConstraint(['departure_id'], ['airport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_departure_time'), 'flight', ['departure_time'], unique=False)
    op.create_index(op.f('ix_flight_end'), 'flight', ['end'], unique=False)
    op.create_index(op.f('ix_flight_number'), 'flight', ['number'], unique=False)
    op.create_index(op.f('ix_flight_start'), 'flight', ['start'], unique=False)
    op.create_table('flight_cancellation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_by', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('purchase_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('assisted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assisted_by'], ['agent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_transaction_email'), 'purchase_transaction', ['email'], unique=False)
    op.create_table('purchased_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('middle_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('refund_timestamp', sa.DateTime(), nullable=True),
    sa.Column('refunded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.id'], ),
    sa.ForeignKeyConstraint(['refunded_by'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['purchase_transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchased_ticket')
    op.drop_index(op.f('ix_purchase_transaction_email'), table_name='purchase_transaction')
    op.drop_table('purchase_transaction')
    op.drop_table('flight_cancellation')
    op.drop_index(op.f('ix_flight_start'), table_name='flight')
    op.drop_index(op.f('ix_flight_number'), table_name='flight')
    op.drop_index(op.f('ix_flight_end'), table_name='flight')
    op.drop_index(op.f('ix_flight_departure_time'), table_name='flight')
    op.drop_table('flight')
    op.drop_table('customer')
    op.drop_table('agent')
    op.drop_table('admin')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_airport_code'), table_name='airport')
    op.drop_table('airport')
    op.drop_index(op.f('ix_airplane_registration_number'), table_name='airplane')
    op.drop_table('airplane')
    # ### end Alembic commands ###
