"""flight dates

Revision ID: b4d8d68a24a7
Revises: e0354dda48e4
Create Date: 2022-06-16 06:52:52.093040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d8d68a24a7'
down_revision = 'e0354dda48e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('start', sa.Date(), nullable=True))
    op.execute("UPDATE flight SET start = DATE('now', 'utc')")
    op.add_column('flight', sa.Column('end', sa.Date(), nullable=True))
    op.execute("UPDATE flight SET end = DATE('now', 'utc', '+180 Day')")
    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.alter_column('start',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('end',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight', 'end')
    op.drop_column('flight', 'start')
    # ### end Alembic commands ###
