"""transaction trip info

Revision ID: c10beb6f188b
Revises: de2666cf1140
Create Date: 2022-07-20 08:31:24.575472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10beb6f188b'
down_revision = 'de2666cf1140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_transaction', sa.Column('departure_id', sa.Integer(), nullable=True))
    op.add_column('purchase_transaction', sa.Column('destination_id', sa.Integer(), nullable=True))
    op.add_column('purchase_transaction', sa.Column('departure_date', sa.Date(), nullable=False))
    op.create_foreign_key('purchase_transaction_ibfk_destination', 'purchase_transaction', 'airport', ['destination_id'], ['id'])
    op.create_foreign_key('purchase_transaction_ibfk_departure', 'purchase_transaction', 'airport', ['departure_id'], ['id'])
    op.drop_column('purchased_ticket', 'departure_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchased_ticket', sa.Column('departure_date', sa.DATE(), nullable=False))
    op.drop_constraint('purchase_transaction_ibfk_destination', 'purchase_transaction', type_='foreignkey')
    op.drop_constraint('purchase_transaction_ibfk_departure', 'purchase_transaction', type_='foreignkey')
    op.drop_column('purchase_transaction', 'departure_date')
    op.drop_column('purchase_transaction', 'destination_id')
    op.drop_column('purchase_transaction', 'departure_id')
    # ### end Alembic commands ###
