"""transactions

Revision ID: d7fa6906eb52
Revises: d9b0732304a7
Create Date: 2022-07-14 15:09:18.642958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7fa6906eb52'
down_revision = 'd9b0732304a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('purchase_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('assisted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assisted_by'], ['agent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_transaction_email'), 'purchase_transaction', ['email'], unique=False)
    op.drop_table('refunded_ticket')
    op.drop_constraint('flight_cancellation_ibfk_1', 'flight_cancellation', type_='foreignkey')
    op.create_foreign_key(None, 'flight_cancellation', 'agent', ['cancelled_by'], ['id'])
    op.add_column('purchased_ticket', sa.Column('transaction_id', sa.Integer(), nullable=False))
    op.add_column('purchased_ticket', sa.Column('first_name', sa.String(length=120), nullable=False))
    op.add_column('purchased_ticket', sa.Column('middle_name', sa.String(length=120), nullable=True))
    op.add_column('purchased_ticket', sa.Column('last_name', sa.String(length=120), nullable=False))
    op.add_column('purchased_ticket', sa.Column('date_of_birth', sa.Date(), nullable=False))
    op.add_column('purchased_ticket', sa.Column('gender', sa.String(length=10), nullable=False))
    op.add_column('purchased_ticket', sa.Column('refund_timestamp', sa.DateTime(), nullable=True))
    op.add_column('purchased_ticket', sa.Column('refunded_by', sa.Integer(), nullable=True))
    op.alter_column('purchased_ticket', 'flight_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index('ix_purchased_ticket_departure_date', table_name='purchased_ticket')
    op.drop_constraint('purchased_ticket_ibfk_3', 'purchased_ticket', type_='foreignkey')
    op.drop_constraint('purchased_ticket_ibfk_1', 'purchased_ticket', type_='foreignkey')
    op.create_foreign_key(None, 'purchased_ticket', 'agent', ['refunded_by'], ['id'])
    op.create_foreign_key(None, 'purchased_ticket', 'purchase_transaction', ['transaction_id'], ['id'])
    op.drop_column('purchased_ticket', 'purchase_timestamp')
    op.drop_column('purchased_ticket', 'assisted_by')
    op.drop_column('purchased_ticket', 'purchased_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchased_ticket', sa.Column('purchased_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('purchased_ticket', sa.Column('assisted_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('purchased_ticket', sa.Column('purchase_timestamp', mysql.DATETIME(), nullable=False))
    op.drop_constraint(None, 'purchased_ticket', type_='foreignkey')
    op.drop_constraint(None, 'purchased_ticket', type_='foreignkey')
    op.create_foreign_key('purchased_ticket_ibfk_1', 'purchased_ticket', 'user', ['assisted_by'], ['id'])
    op.create_foreign_key('purchased_ticket_ibfk_3', 'purchased_ticket', 'user', ['purchased_by'], ['id'])
    op.create_index('ix_purchased_ticket_departure_date', 'purchased_ticket', ['departure_date'], unique=False)
    op.alter_column('purchased_ticket', 'flight_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('purchased_ticket', 'refunded_by')
    op.drop_column('purchased_ticket', 'refund_timestamp')
    op.drop_column('purchased_ticket', 'gender')
    op.drop_column('purchased_ticket', 'date_of_birth')
    op.drop_column('purchased_ticket', 'last_name')
    op.drop_column('purchased_ticket', 'middle_name')
    op.drop_column('purchased_ticket', 'first_name')
    op.drop_column('purchased_ticket', 'transaction_id')
    op.drop_constraint(None, 'flight_cancellation', type_='foreignkey')
    op.create_foreign_key('flight_cancellation_ibfk_1', 'flight_cancellation', 'user', ['cancelled_by'], ['id'])
    op.create_table('refunded_ticket',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('refund_timestamp', mysql.DATETIME(), nullable=False),
    sa.Column('refund_amount', mysql.FLOAT(), nullable=False),
    sa.Column('refunded_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['refunded_by'], ['user.id'], name='refunded_ticket_ibfk_1'),
    sa.ForeignKeyConstraint(['ticket_id'], ['purchased_ticket.id'], name='refunded_ticket_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_purchase_transaction_email'), table_name='purchase_transaction')
    op.drop_table('purchase_transaction')
    # ### end Alembic commands ###
