"""confirmation number

Revision ID: de2666cf1140
Revises: ea96fe53b784
Create Date: 2022-07-17 16:57:29.384782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de2666cf1140'
down_revision = 'ea96fe53b784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_transaction', sa.Column('confirmation_number', sa.String(length=6), nullable=False))
    op.alter_column('purchase_transaction', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.create_unique_constraint('_pnr', 'purchase_transaction', ['email', 'confirmation_number'])
    op.create_index(op.f('ix_purchase_transaction_confirmation_number'), 'purchase_transaction', ['confirmation_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_transaction_confirmation_number'), table_name='purchase_transaction')
    op.drop_constraint('_pnr', 'purchase_transaction', type_='unique')
    op.alter_column('purchase_transaction', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.drop_column('purchase_transaction', 'confirmation_number')
    # ### end Alembic commands ###
