"""transaction price

Revision ID: ea96fe53b784
Revises: a736dd8077fe
Create Date: 2022-07-17 09:08:06.730076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea96fe53b784'
down_revision = 'a736dd8077fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_transaction', sa.Column('base_fare', sa.Float(), nullable=False))
    op.add_column('purchase_transaction', sa.Column('purchase_price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_transaction', 'purchase_price')
    op.drop_column('purchase_transaction', 'base_fare')
    # ### end Alembic commands ###
